### ISSUE TITLE
what port ?

### ISSUE THREAD

**Issue by ghost** [influx6/clis#2]
have Terminal tell me what port its running on. I have to guess at the moment :)

**Comment by influx6** [comment]
Just specify the port you want by setting -addr CLI option

**Comment by ghost** [comment]
i tried that, but it did not work.

**Comment by influx6** [comment]
Updated readme to provide basic usage steps.

**Comment by influx6** [comment]
See readme https://github.com/influx6/clis/blob/master/servex/readme.md
